services:  
  - type: web
    name: elysiajs-hello-world
    runtime: node
    repo: https://github.com/p1xlized/biblio-api
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.34
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
